/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rayboot_scantool_cv_OpenCVManager */

#ifndef _Included_com_rayboot_scantool_cv_OpenCVManager
#define _Included_com_rayboot_scantool_cv_OpenCVManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rayboot_scantool_cv_OpenCVManager_MSG_IMAGE_SCAN
#define com_rayboot_scantool_cv_OpenCVManager_MSG_IMAGE_SCAN 1L
#undef com_rayboot_scantool_cv_OpenCVManager_MSG_IMAGE_CROP
#define com_rayboot_scantool_cv_OpenCVManager_MSG_IMAGE_CROP 2L
/*
 * Class:     com_rayboot_scantool_cv_OpenCVManager
 * Method:    nScan
 * Signature: (Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_rayboot_scantool_cv_OpenCVManager_nScan
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rayboot_scantool_cv_OpenCVManager
 * Method:    nCrop
 * Signature: (Ljava/lang/String;[[I[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rayboot_scantool_cv_OpenCVManager_nCrop
  (JNIEnv *, jclass, jstring, jobjectArray, jintArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
